# Generated by Django 6.0.6 on 2026-06-14 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='correct_words',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='guess',
            name='guessed_words',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='guess',
            name='score_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='guess_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('author', 'post')},
        ),
    ]
